---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  require_ansible_repo: true
  ansible_verbose: true
  playbook: tests/test.yml
  hosts: localhost
  extra_vars:
    threatstack_deploy_key: <%= ENV['TS_DEPLOY_KEY'] != nil ? ENV['TS_DEPLOY_KEY'] : 'ts_deploy_key' %>
    threatstack_agent_config_args: <%= ENV['TS_CONFIG_ARGS'] %>


platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: debian-7.8
  - name: centos-6.7

suites:
  - name: default
