language: python
python: '2.7'
sudo: required

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-apt
install:
  - pip install ansible
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"
script:
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check
  - ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo
  - ansible-playbook -i tests/inventory tests/test.yml --check --diff --connection=local --sudo
  - "ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo |
    tee /tmp/output.txt; grep -q 'changed=0.*failed=0' /tmp/output.txt && (echo 'Idempotence test: pass' && exit 0) ||
    (echo 'Idempotence test: fail' && exit 1)"

env:
  global:
    secure: "Ofu8qn7PqRgl7+1d90fHT50OLdLiWfHbFP6eeVXa8q59/4maWmcI+uyz2Wn6pGOGiavgj+AoCzNh7KIsq9RQsmg/3JtgrfjDfh38dTRo8E/1BgijYCNrZNPG6KGSDJuO8qM/AGWF57/0qBX7X9ndbZl/e9TuxjYPn1DjRrhyYog="
