language: python
python: '2.7'
before_install:
- sudo apt-get update -qq
- sudo apt-get install -y curl
install:
- pip install ansible
- "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"
script:
- ansible-playbook -i tests/inventory tests/test.yml --syntax-check
- ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo
- 'ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo |
  grep -q ''changed=0.*failed=0'' && (echo ''Idempotence test: pass'' && exit 0) ||
  (echo ''Idempotence test: fail'' && exit 1)

'
notifications:
  email: false
env:
  secure: KRC3V+30bVvKILfxzBB3oobV/9jZxQHhg9pKnd0vyGbByGb/VlwxKpTgIcMfJatb7gvJAm7FSiwiS7tv4x9KrRi7sR7npxFYqjt8njQ0jG1WPjwHfTDW++3j/XpcIcS8grSjnKxKSC7Uy4uEajsE+dhvBtZm1QyUvitf5iQg50M=
