---
- name: Install setup dependency.
  apt:
    name: python-apt
    update_cache: yes
    state: installed
    tags:
      - travis-non-idempotent

- name: Add Threat Stack apt repository key.
  apt_key:
    url: https://app.threatstack.com/APT-GPG-KEY-THREATSTACK
    id: 6EE04BD4
    validate_certs: no

- name: Add Threat Stack apt repository.
  apt_repository:
    repo: "deb {{ threatstack_pkg_url }}/Ubuntu {{ ansible_distribution_release }} main"
    state: present
    update_cache: yes

- name: Ensure Threat Stack is installed.
  apt:
    name: "{{ threatstack_pkg }}"
    state: "{{ threatstack_pkg_state }}"
