---

# Cloudsight Setup
- name: Create Threat Stack Config Directory
  file: path="{{ threatstack_config_dir }}" state=directory owner=root group=root mode=0644 recurse=yes

- name: Create ThreatStack Config File
  template:
    src: templates/config.j2
    dest: "{{ threatstack_config }}"
    owner: root
    group: root
    mode: 0644

- name: Cloudsight - setup default
  command: cloudsight setup --config="{{ threatstack_config }}"
  register: setup_result
  failed_when: setup_result.stderr and 'FAILED' in setup_result.stderr
  args:
    creates: /opt/threatstack/cloudsight/config/.secret

# Test
- name: Test cloudsight state
  service:
    name: cloudsight
    enabled: yes
    state: started
