---
# Setup tasks
- name: Run Apt configure and install Threat Stack
  include: apt_install.yml
  when: ansible_os_family == 'Debian'

- name: Run Yum Configure and install Threat Stack
  include: yum_install.yml
  when: ansible_os_family == 'RedHat'

- name: 1.x agent setup
  include: cloudsight_setup.yml
  when:
    - threatstack_configure_agent == true
    - not threatstack_v2

- name: 2.x agent setup
  include: tsagent_setup.yml
  when:
    - threatstack_configure_agent == true
    - threatstack_v2
